### ISSUE TITLE
Visualization of clustering results 

### ISSUE THREAD

**Issue by YunCL** [XifengGuo/IDEC#1]
hello, how to visualize the clustering results in your paper?Thank you.

**Comment by XifengGuo** [comment]
@YunCL 

[tsne-vis.zip](https://github.com/XifengGuo/IDEC/files/1588397/tsne-vis.zip)

**Comment by hammad97** [comment]
How can we view clusters if there is no ground truth(y) and only thing i got are features(x)? Since my program works unsupervised and i donot have ground truth of my dataset.

**Comment by yangshichong** [comment]
Hello,I tested this code : tsne-vis.zip, but I got the following error:   
Traceback (most recent call last):
  File "G:/CODE/python/DeepClustering/IDEC/tsne-vis.py", line 13, in <module>
    dec.load_weights('IDEC_model_final.h5')
  File "G:\CODE\python\DeepClustering\IDEC\IDEC.py", line 84, in load_weights
    self.model.load_weights(weights_path)
AttributeError: 'IDEC' object has no attribute 'model'
I am using python 3.5.6, tensorflow-gpu version 1.10.0 and keras 2.2.2, could you tell me how to ues this       code? Thank you.
@XifengGuo

**Comment by guneetmutreja** [comment]
> Hello,I tested this code : tsne-vis.zip, but I got the following error: Traceback (most recent call last): File "G:/CODE/python/DeepClustering/IDEC/tsne-vis.py", line 13, in dec.load_weights('IDEC_model_final.h5') File "G:\CODE\python\DeepClustering\IDEC\IDEC.py", line 84, in load_weights self.model.load_weights(weights_path) AttributeError: 'IDEC' object has no attribute 'model' I am using python 3.5.6, tensorflow-gpu version 1.10.0 and keras 2.2.2, could you tell me how to ues this code? Thank you. @XifengGuo

Hey, were you able to solve it?

**Comment by yangshichong** [comment]
您好，您的邮件我已收到，我会尽快处理。                                                               杨士冲
