### ISSUE TITLE
REUTERS data not available

### ISSUE THREAD

**Issue by inigo-jauregi** [XifengGuo/IDEC#3]
Hi!

I've tried to download REUTERS data with the get_data.sh script you have provided, but it seems the files are not available there anymore. Do you how I could get that data?

Thank you very much in advance!

**Comment by XifengGuo** [comment]
@ijauregiCMCRC I have a backup for Reuters on https://pan.baidu.com/s/1hsMQ8Tm (password: 4ss4)

**Comment by inigo-jauregi** [comment]
thanks @XifengGuo !
